apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: devops
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgres://postgres:drow@postgres-postgresql-0.devops.svc.cluster.local:5432/devops?sslmode=disable"
