adminUser: admin
adminPassword: drow
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.devops.local
  tls: []
  annotations:
    kubernetes.io/ingress.class: traefik
image:
  pullPolicy: IfNotPresent
persistence:
  enabled: true
  size: 1Gi
